# Cosine 

In [1]:
import numpy as np
import pandas as pd
from forgebox.category import Category

## Cosine Similarity

In [2]:
from forgebox.cosine import CosineSearch, CosineSearchWithCategory

## Test search

In [3]:
base = np.random.rand(50000,100)-.2
vec = base[200]

In [4]:
cosine = CosineSearch(base)

In [5]:
cosine(vec)

array([  200, 45841, 49488, ..., 37457, 31116, 45770])

In [6]:
cosine.search(vec, return_similarity=True)

(array([  200, 45841, 49488, ..., 37457, 31116, 45770]),
 array([0.22080708, 0.16454399, 0.16373655, ..., 0.07275872, 0.06884953,
        0.06865599]))

In [8]:
%%time
for i in range(100):
    cosine(vec)

CPU times: user 1.37 s, sys: 283 ms, total: 1.66 s
Wall time: 1.72 s
